# 1.Linear Algebra

In [ ]:
#Scalar

a = 1

#Vector
[1,2,3]
#Matrix
[[1,2],
 [3,4]]
#Tensor
[ [[1,2,3],[4,5,6],[7,8,9]],
  [[1,2,3],[4,5,6],[7,8,9]]]

In [1]:
import numpy as np

In [2]:
a = np.zeros((3,2)) # matrix 0 3 row 2 columns

In [3]:
a.shape # dim Check

(3, 2)

In [4]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
b = np.zeros((2, 3, 4)) # row columns numpy
b

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

# 2.Matrix multiplication

In [6]:
c = np.array([[4,0],
              [1,-9]])

In [8]:
x = np.array([[1, 2],
              [4, 5]])
y = np.array([[2, 3],
              [5, 6]])
z = 2*x
z

array([[ 2,  4],
       [ 8, 10]])

In [14]:
#Matrix addition
z = x + y  
# np.add(x,y) # + กันตรงแถวตรงหลัก
# np.devide(x,y) # หารกันตรงแถวตรงหลัก
np.multiply(x,y)  # คูณกันตรงแถวตรงหลัก


array([[ 2,  6],
       [20, 30]])

In [10]:
z

array([[ 3,  5],
       [ 9, 11]])

In [29]:
x = np.array([1, 2, 3])
y = np.array([3, 4, 5])
np.dot(x, y) # 1*3+2*4+3*5 Shape?

26

In [30]:
np.cross(y, x)

array([ 2, -4,  2])

In [32]:
x.shape = (3,1) # กำหนดให้เป็นtranspose หรือ ใช้ x.T

In [34]:
x_new = x

In [35]:
x_new.T

array([[1, 2, 3]])

In [36]:
# outer (x.T, y) # คล้ายๆ matrix ทำ factorization
a = np.array([[5,1,3],
              [1,1,1],
              [1,2,1]])
print(a.shape)

b = np.array([1,2,3])
print(a.dot(b))

[16  6  8]


In [37]:
a.shape

(3, 3)

In [39]:
A = [[1,0], 
     [0,1]]
B = [[4,1], 
     [2,2]]
print(type(A))
np.matmul(A,B) # อย่าลืมว่า col ของตัวตั้ง ต้องเท่ากับ row ตัวคูณ

<class 'list'>


array([[4, 1],
       [2, 2]])

In [42]:
matrixA = np.array(A)
matrixB = np.array(B)
C = matrixA - matrixB
print(C)

[[-3 -1]
 [-2 -1]]


In [44]:
A1 = [[1, 2, 3],
      [4, 5, 6],
      [7, 8 ,9]]
B1 = [[9, 8, 7],
      [6, 5, 4],
      [3, 2, 1]]
np.matmul(A1,B1) 

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

# 3. Identity matrix

In [50]:
# identity matrix I
idt = np.array([[1,2],
                [3,4]])

y = np.identity(3, dtype=int)
y

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [74]:
A = np.matrix([[1,2],
               [4,5]])
A_1= np.linalg.inv(A)

In [69]:
np.linalg.inv(y)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [70]:
B = np.matrix([[1,2,3],
               [4,5,6]])

In [71]:
np.linalg.inv(B)

LinAlgError: Last 2 dimensions of the array must be square

In [76]:
A_1*A

matrix([[1.00000000e+00, 1.11022302e-16],
        [0.00000000e+00, 1.00000000e+00]])