# L A B

In [4]:
import numpy as np

g = 9.81  # gravity force
m = 1500  # mass
lz = 3000  #
Caf = 19000  # Car front
Car = 33000  # Car right
lf = 2  # Lateral font wheel
lr = 3  # lateral right wheel
Ts = 0.02  # Time sample
x_dot = 20

A1 = -(2*Caf + 2*Car)/(m*x_dot)
A2 = -x_dot-(2*Caf*lf-2*Car*lr)/(m*x_dot)
A3 = -(2*lf*Caf-2*lr*Car)/(lz*x_dot)
A4 = -(2*lf**2*Caf+2*lr**2*Car)/(lz*x_dot)


In [17]:


A = np.array([[A1,  0, A2, 0],
              [0,  0,  1, 0],
              [A3, 0, A4, 0],
              [1, x_dot, 0, 0]])

B = np.array([[2*Caf/m], [0], [2*lf*Caf/lz], [0]])

C = np.array([[0, 1, 0, 0],
             [0, 0, 0, 1]])

D = 0

Ad = np.identity(np.size(A,1)) + Ts*A
Bd = Ts*B
Cd = C
Dd = D

A_aug = np.concatenate((Ad, Bd), axis=1)
temp1 = np.zeros((np.size(Bd,1), np.size(Ad, 1)))
temp2 = np.identity(np.size(Bd, 1))
temp = np.concatenate((temp1, temp2), axis=1)

A_aug = np.concatenate((A_aug,temp), axis=0)
B_aug = np.concatenate((Bd, np.identity(np.size(Bd, 1))), axis=0)
C_aug = np.concatenate((Cd, np.zeros((np.size(Cd, 0), np.size(Bd, 1)))), axis=1)
D_aug = Dd

np.size(A,1)

4

In [23]:
A_aug = np.concatenate((Ad, Bd), axis=1)
print(Ad)
print(Bd)
print(A_aug)

[[ 0.93066667  0.         -0.31866667  0.        ]
 [ 0.          1.          0.02        0.        ]
 [ 0.04066667  0.          0.75133333  0.        ]
 [ 0.02        0.4         0.          1.        ]]
[[0.50666667]
 [0.        ]
 [0.50666667]
 [0.        ]]
[[ 0.93066667  0.         -0.31866667  0.          0.50666667]
 [ 0.          1.          0.02        0.          0.        ]
 [ 0.04066667  0.          0.75133333  0.          0.50666667]
 [ 0.02        0.4         0.          1.          0.        ]]


TypeError: Cannot interpret '1' as a data type

In [20]:
Ad = np.identity(np.size(A, 1)) + Ts * A

In [13]:
np.size(A,1)

4